[project]
name = ""
version = ""
description = ""
authors = [
    {name = "sovlookup", email = "gonorth@qq.com"},
]
dependencies = [
    "paddlespeech>=1.0.1",
    "paddlepaddle>=2.3.1",
]
requires-python = ">=3.8"
license = {text = "MIT"}

[tool.pdm]

[tool.pdm.scripts]
start = "python src/main.py"

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
