name: ci

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
        
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: ${{ secrets.DOCKERHUB_USERNAME }}/ppasr:latest
          platform: linux/amd64,linux/arm64
          dockerUser: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerPassword: ${{ secrets.DOCKERHUB_TOKEN }}
                
